//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeePower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Employee_Login_Details
    {
        public int Emp_ID { get; set; }
        public string Emp_FirstName { get; set; }
        public string Emp_LastName { get; set; }
        public string Emp_Email { get; set; }
        public Nullable<bool> Emp_Email_Confirm { get; set; }
        public Nullable<int> Emp_MobileNo { get; set; }
        public Nullable<bool> Emp_MobilieNo_Confirm { get; set; }
        public Nullable<int> Emp_Alt_MobileNo { get; set; }
        public string Emp_Password_Hash { get; set; }
        public string Emp_Account_Status { get; set; }
        public string Emp_Created_By { get; set; }
        public Nullable<System.DateTime> Emp_Created_Date { get; set; }
        public string Emp_Updated_By { get; set; }
        public Nullable<System.DateTime> Emp_Updated_Date { get; set; }
    }
}
